language: python
cache: pip

matrix:
  include:
    - python: 3.7
      dist: xenial
    - python: 3.6
    - python: pypy3
  fast_finish: true

install:
 - pip install --upgrade pip
 - pip install --upgrade black flake8
 - pip install --upgrade -r requirements.txt

script:
  # Unit tests
  - python test_fng.py
  - python test_artists.py

  # Static analysis
  - flake8
  - black . --check --diff
