language: python
cache: pip

matrix:
  include:
    - python: 3.7
      dist: xenial
    - python: 3.6
  fast_finish: true

install:
 - pip install --upgrade pip
 - pip install --upgrade black flake8 pytest
 - pip install --upgrade -r requirements.txt

script:
  # Unit tests
  - pytest

  # Static analysis
  - flake8
  - black . --check --diff
