language: python

python:
  - 2.7
  - 3.6
  - 3.5
  - 3.4
  - "pypy"
  - "pypy3"

sudo: false

script:
  - python test_fng.py
  - python test_artists.py

after_success:
  - pip install pep8 pyflakes
  - pep8 *.py
  - pyflakes *.py

matrix:
  allow_failures:
    - python: 3.6
    - python: 3.5
    - python: 3.4
    - python: "pypy"
    - python: "pypy3"
