language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - "pypy"

script:
  - python test_fng.py

after_success:
  - pip install pep8 pyflakes
  - pep8 *.py
  - pyflakes *.py

matrix:
  allow_failures:
    - python: 2.6
    - python: 3.2
    - python: 3.3
    - python: 3.4
    - python: "pypy"
